# Example 05: Get a datasets for multiple series and countries from ILO API in csv format

Download csvs from ILO's SDMX API (ILOSTAT SDMX Gateway).

### Load required libraries

In [2]:
import json
import requests 
import os
from bs4 import BeautifulSoup
import re
import pandas as pd

### Create folder for data

In [11]:
os.mkdir('..\\data\\UNESCO_UIS_Metadata')

### Use email (old indicators) and dictionary to create new indicators

In [4]:
df = pd.read_excel('..\\data\\UNESCO_UIS_indicators\\uis-data-dictionary-education-statistics.xlsx',sheet_name = 'Students and Teachers')
idctr = pd.read_csv('..\\data\\UNESCO_UIS_indicators\\email.csv')
idctr.Old_Code = [i.replace('_','.') for i in idctr.Old_Code]
New_list = []
for i in idctr.Old_Code:
    a = 'UNESCO,EDU_NON_FINANCE,3.0/'
    for s in df[df["Indicator ID"].str.lower() == i.lower()].iloc[0,6:-2]:
        a = a  + str(s) +'.'
    New_list.append(a)
idctr.New_Code = New_list
idctr

,Indicator,Disaggregation,Old_Code,New_Code
0,20. Youth literacy rate of persons (15-24 year...,Both_sexes,LR.Ag15t24,"UNESCO,EDU_NON_FINANCE,3.0/LR.PT._Z._Z._T.Y15T..."
1,20. Youth literacy rate of persons (15-24 year...,Female,LR.Ag15t24.F,"UNESCO,EDU_NON_FINANCE,3.0/LR.PT._Z._Z.F.Y15T2..."
2,20. Youth literacy rate of persons (15-24 year...,Male,LR.Ag15t24.M,"UNESCO,EDU_NON_FINANCE,3.0/LR.PT._Z._Z.M.Y15T2..."
3,20. Youth literacy rate of persons (15-24 year...,GPI,LR.Ag15t24.gpi,"UNESCO,EDU_NON_FINANCE,3.0/LR.GPI._Z._Z._T.Y15..."
4,21. Adjusted net enrolment rate in primary edu...,Both_sexes,NERA.1.cp,"UNESCO,EDU_NON_FINANCE,3.0/NERA.PT.L1._T._T.SC..."
5,21. Adjusted net enrolment rate in primary edu...,Female,NERA.1.F.cp,"UNESCO,EDU_NON_FINANCE,3.0/NERA.PT.L1._T.F.SCH..."
6,21. Adjusted net enrolment rate in primary edu...,Male,NERA.1.M.cp,"UNESCO,EDU_NON_FINANCE,3.0/NERA.PT.L1._T.M.SCH..."
7,21. Adjusted net enrolment rate in primary edu...,GPI,NERA.1.gpi,"UNESCO,EDU_NON_FINANCE,3.0/NERA.GPI.L1._T._T.S..."
8,22.Gross enrolment ratio in secondary educatio...,Both_sexes,GER.2t3,"UNESCO,EDU_NON_FINANCE,3.0/GER.PT.L2_3._T._T.S..."
9,22.Gross enrolment ratio in secondary educatio...,Female,GER.2t3.F,"UNESCO,EDU_NON_FINANCE,3.0/GER.PT.L2_3._T.F.SC..."
10,22.Gross enrolment ratio in secondary educatio...,Male,GER.2t3.M,"UNESCO,EDU_NON_FINANCE,3.0/GER.PT.L2_3._T.M.SC..."
11,23. Gross enrolment ratio in tertiary educatio...,Both_sexes,GER.5t8,"UNESCO,EDU_NON_FINANCE,3.0/GER.PT.L5T8._T._T.S..."
12,23. Gross enrolment ratio in tertiary educatio...,Female,GER.5t8.F,"UNESCO,EDU_NON_FINANCE,3.0/GER.PT.L5T8._T.F.SC..."
13,23. Gross enrolment ratio in tertiary educatio...,Male,GER.5t8.M,"UNESCO,EDU_NON_FINANCE,3.0/GER.PT.L5T8._T.M.SC..."
14,24a. Gender parity index of the gross enrolmen...,GPI,GER.1.gpi,"UNESCO,EDU_NON_FINANCE,3.0/GER.GPI.L1._T._T.SC..."
15,24b. Gender parity index of the gross enrolmen...,GPI,GER.2t3.gpi,"UNESCO,EDU_NON_FINANCE,3.0/GER.GPI.L2_3._T._T...."
16,24c. Gender parity index of the gross enrolmen...,GPI,GER.5t8.gpi,"UNESCO,EDU_NON_FINANCE,3.0/GER.GPI.L5T8._T._T...."
17,"25.Share of female science, technology , engin...",Female,FGP.5T8.F500600700,"UNESCO,EDU_NON_FINANCE,3.0/FGP.PT.L5T8._T.F._T..."
18,26.Proportion of females among tertiary educat...,GPI,FTP.5t8,"UNESCO,EDU_NON_FINANCE,3.0/FTP.PT.L5T8._T.F._T..."
19,27. Adjusted net intake rate to the first grad...,Both_sexes,NIRA.1.cp,"UNESCO,EDU_NON_FINANCE,3.0/NIRA.PT.L1._T._T.TH..."
20,27. Adjusted net intake rate to the first grad...,Female,NIRA.1.F.cp,"UNESCO,EDU_NON_FINANCE,3.0/NIRA.PT.L1._T.F.TH_..."
21,27. Adjusted net intake rate to the first grad...,Male,NIRA.1.M.cp,"UNESCO,EDU_NON_FINANCE,3.0/NIRA.PT.L1._T.M.TH_..."
22,27. Adjusted net intake rate to the first grad...,GPI,NIRA.1.gpi,"UNESCO,EDU_NON_FINANCE,3.0/NIRA.GPI.L1._T._T.T..."
23,"28. Primary education completion rate (proxy),...",Both_sexes,AIR.1.Glast,"UNESCO,EDU_NON_FINANCE,3.0/AIR.PT.L1._T._T._T...."
24,"28. Primary education completion rate (proxy),...",Female,AIR.1.Glast.F,"UNESCO,EDU_NON_FINANCE,3.0/AIR.PT.L1._T.F._T.G..."
25,"28. Primary education completion rate (proxy),...",Male,AIR.1.Glast.M,"UNESCO,EDU_NON_FINANCE,3.0/AIR.PT.L1._T.M._T.G..."
26,"28. Primary education completion rate (proxy),...",GPI,AIR.1.Glast.gpi,"UNESCO,EDU_NON_FINANCE,3.0/AIR.GPI.L1._T._T._T..."
27,29. Gross graduation ratio from lower secondar...,Both_sexes,GGR.2,"UNESCO,EDU_NON_FINANCE,3.0/GGR.PT.L2._T._T._T...."
28,29. Gross graduation ratio from lower secondar...,Female,GGR.2.F,"UNESCO,EDU_NON_FINANCE,3.0/GGR.PT.L2._T.F._T.G..."
29,29. Gross graduation ratio from lower secondar...,Male,GGR.2.M,"UNESCO,EDU_NON_FINANCE,3.0/GGR.PT.L2._T.M._T.G..."
30,29. Gross graduation ratio from lower secondar...,GPI,GGR.2.gpi,"UNESCO,EDU_NON_FINANCE,3.0/GGR.GPI.L2._T._T._T..."
31,30. Effective transition rate from primary to ...,Both_sexes,TRANRA.2.GPV.CP,"UNESCO,EDU_NON_FINANCE,3.0/TRANRA.PT.L2.C4._T...."
32,30. Effective transition rate from primary to ...,Female,TRANRA.2.GPV.F.CP,"UNESCO,EDU_NON_FINANCE,3.0/TRANRA.PT.L2.C4.F._..."
33,30. Effective transition rate from primary to ...,Male,TRANRA.2.GPV.M.CP,"UNESCO,EDU_NON_FINANCE,3.0/TRANRA.PT.L2.C4.M._..."
34,30. Effective transition rate from primary to ...,GPI,TRANRA.2.GPV.GPI,"UNESCO,EDU_NON_FINANCE,3.0/TRANRA.GPI.L2.C4._T..."
35,31a. Cumulative Educational attainment (minimu...,Both_sexes,EA.1t8.AG25t99,"UNESCO,EDU_NON_FINANCE,3.0/EA.PT._Z._Z._T.Y_GE..."
36,31a. Cumulative Educational attainment (minimu...,Female,EA.1t8.AG25t99.F,"UNESCO,EDU_NON_FINANCE,3.0/EA.PT._Z._Z.F.Y_GE2..."
37,31a. Cumulative Educational attainment (minimu...,Male,EA.1t8.AG25t99.M,"UNESCO,EDU_NON_FINANCE,3.0/EA.PT._Z._Z.M.Y_GE2..."
38,31a. Cumulative Educational attainment (minimu...,GPI,EA.1t8.AG25t99.gpi,"UNESCO,EDU_NON_FINANCE,3.0/EA.GPI._Z._Z._T.Y_G..."
39,31b. Cumulative Educational attainment (minimu...,Both_sexes,EA.2t8.AG25t99,"UNESCO,EDU_NON_FINANCE,3.0/EA.PT._Z._Z._T.Y_GE..."
40,31b. Cumulative Educational attainment (minimu...,Female,EA.2t8.AG25t99.F,"UNESCO,EDU_NON_FINANCE,3.0/EA.PT._Z._Z.F.Y_GE2..."
41,31b. Cumulative Educational attainment (minimu...,Male,EA.2t8.AG25t99.M,"UNESCO,EDU_NON_FINANCE,3.0/EA.PT._Z._Z.M.Y_GE2..."
42,31b. Cumulative Educational attainment (minimu...,GPI,EA.2t8.AG25t99.gpi,"UNESCO,EDU_NON_FINANCE,3.0/EA.GPI._Z._Z._T.Y_G..."
43,31c. Cumulative Educational attainment (minimu...,Both_sexes,EA.3t8.AG25t99,"UNESCO,EDU_NON_FINANCE,3.0/EA.PT._Z._Z._T.Y_GE..."
44,31c. Cumulative Educational attainment (minimu...,Female,EA.3t8.AG25t99.F,"UNESCO,EDU_NON_FINANCE,3.0/EA.PT._Z._Z.F.Y_GE2..."
45,31c. Cumulative Educational attainment (minimu...,Male,EA.3t8.AG25t99.M,"UNESCO,EDU_NON_FINANCE,3.0/EA.PT._Z._Z.M.Y_GE2..."
46,31c. Cumulative Educational attainment (minimu...,GPI,EA.3t8.AG25t99.gpi,"UNESCO,EDU_NON_FINANCE,3.0/EA.GPI._Z._Z._T.Y_G..."
47,31d. Cumulative Educational attainment (minimu...,Both_sexes,EA.4t8.AG25t99,"UNESCO,EDU_NON_FINANCE,3.0/EA.PT._Z._Z._T.Y_GE..."
48,31d. Cumulative Educational attainment (minimu...,Female,EA.4t8.AG25t99.F,"UNESCO,EDU_NON_FINANCE,3.0/EA.PT._Z._Z.F.Y_GE2..."
49,31d. Cumulative Educational attainment (minimu...,Male,EA.4t8.AG25t99.M,"UNESCO,EDU_NON_FINANCE,3.0/EA.PT._Z._Z.M.Y_GE2..."
50,31d. Cumulative Educational attainment (minimu...,GPI,EA.4t8.AG25t99.gpi,"UNESCO,EDU_NON_FINANCE,3.0/EA.GPI._Z._Z._T.Y_G..."
51,31e. Cumulative Educational attainment (minimu...,Both_sexes,EA.5t8.AG25t99,"UNESCO,EDU_NON_FINANCE,3.0/EA.PT._Z._Z._T.Y_GE..."
52,31e. Cumulative Educational attainment (minimu...,Female,EA.5t8.AG25t99.F,"UNESCO,EDU_NON_FINANCE,3.0/EA.PT._Z._Z.F.Y_GE2..."
53,31e. Cumulative Educational attainment (minimu...,Male,EA.5t8.AG25t99.M,"UNESCO,EDU_NON_FINANCE,3.0/EA.PT._Z._Z.M.Y_GE2..."
54,31e. Cumulative Educational attainment (minimu...,GPI,EA.5t8.AG25t99.gpi,"UNESCO,EDU_NON_FINANCE,3.0/EA.GPI._Z._Z._T.Y_G..."

### Interactive shell

In [5]:
# https://volderette.de/jupyter-notebook-tip-multiple-outputs/
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [6]:
############### put your api key here ####################
key = 'eacdf60587ba47a092eaf020b4bd42f5'



headers ={'Ocp-Apim-Subscription-key': key}

### find the meta-data dictionary for the specific indicator

In [12]:
url = 'https://api.uis.unesco.org/sdmx/data/UNESCO,EDU_NON_FINANCE,3.0/LR.PT._Z._Z._T.Y15T24._Z._Z._Z._Z._T._Z._Z._Z._Z._Z._Z._Z.W00.W00._Z.?startPeriod=2000&endPeriod=2018&format=sdmx-json&includeMetadata=true&locale=en'
# this is a trial
resp = requests.get(url,headers = headers) 

doc = resp.json()
type(doc)
file = '..\\data\\UNESCO_UIS_Metadata\\UNESCO_Metadata.json'
with open(file, 'w') as json_file:
    json.dump(doc, json_file)

dict

In [13]:
print('---Root:')
len(doc)
rootKey = list(doc.keys())[2]
rootKey

print('---Level 1: / structure')
level1 = doc[rootKey]
len(level1)
level1Keys = list(level1.keys())
level1Keys

print('---Level 2 / name')
level2 = level1['dimensions']
len(level2)
level2Keys = list(level2.keys())
level2Keys

print('---Level 3 / series')
level3 = level2['series']
len(level3)
level3

---Root:

3

'structure'

---Level 1: / structure

4

['name', 'description', 'dimensions', 'attributes']

---Level 2 / name

3

['dataset', 'series', 'observation']

---Level 3 / series

22

[{'id': 'STAT_UNIT',
  'name': 'Statistical unit',
  'description': 'Entity for which information is sought and for which statistics are ultimately compiled.',
  'keyPosition': 0,
  'role': None,
  'values': [{'position': 18, 'id': 'LR', 'name': 'Literacy rate'}]},
 {'id': 'UNIT_MEASURE',
  'name': 'Unit of measure',
  'description': 'The unit in which the data values are measured.',
  'keyPosition': 1,
  'role': None,
  'values': [{'position': 6, 'id': 'PT', 'name': 'Percentage'}]},
 {'id': 'EDU_LEVEL',
  'name': 'Level of education',
  'keyPosition': 2,
  'role': None,
  'values': [{'position': 21, 'id': '_Z', 'name': 'Not applicable'}]},
 {'id': 'EDU_CAT',
  'name': 'Orientation',
  'keyPosition': 3,
  'role': None,
  'values': [{'position': 4, 'id': '_Z', 'name': 'Not applicable'}]},
 {'id': 'SEX',
  'name': 'Sex',
  'description': 'The state of being male or female.',
  'keyPosition': 4,
  'role': None,
  'values': [{'position': 4, 'id': '_T', 'name': 'Total'}]},
 {'id': 'AGE',
  'name': 'Age',
  'description': 'The length of time that a person has lived or a thing has existed.',
  'keyPosition': 5,
  'role': None,
  'values': [{'position': 5, 'id': 'Y15T24', 'name': '15-24 years'}]},
 {'id': 'GRADE',
  'name': 'Grade',
  'keyPosition': 6,
  'role': None,
  'values': [{'position': 11, 'id': '_Z', 'name': 'Not applicable'}]},
 {'id': 'SECTOR_EDU',
  'name': 'Type of institution',
  'keyPosition': 7,
  'role': None,
  'values': [{'position': 5, 'id': '_Z', 'name': 'Not applicable'}]},
 {'id': 'EDU_ATTAIN',
  'name': 'Level of educational attainment',
  'keyPosition': 8,
  'role': None,
  'values': [{'position': 16, 'id': '_Z', 'name': 'Not applicable'}]},
 {'id': 'WEALTH_QUINTILE',
  'name': 'Wealth quintile',
  'keyPosition': 9,
  'role': None,
  'values': [{'position': 7, 'id': '_Z', 'name': 'Not applicable'}]},
 {'id': 'LOCATION',
  'name': 'Location',
  'keyPosition': 10,
  'role': None,
  'values': [{'position': 1, 'id': '_T', 'name': 'Total'}]},
 {'id': 'EDU_TYPE',
  'name': 'Type of education',
  'keyPosition': 11,
  'role': None,
  'values': [{'position': 4, 'id': '_Z', 'name': 'Not applicable'}]},
 {'id': 'EDU_FIELD',
  'name': 'Field of education',
  'keyPosition': 12,
  'role': None,
  'values': [{'position': 3, 'id': '_Z', 'name': 'Not applicable'}]},
 {'id': 'SUBJECT',
  'name': 'School subject',
  'keyPosition': 13,
  'role': None,
  'values': [{'position': 4, 'id': '_Z', 'name': 'Not applicable'}]},
 {'id': 'INFRASTR',
  'name': 'Infrastructure',
  'keyPosition': 14,
  'role': None,
  'values': [{'position': 6, 'id': '_Z', 'name': 'Not applicable'}]},
 {'id': 'SE_BKGRD',
  'name': 'Socioeconomic background',
  'keyPosition': 15,
  'role': None,
  'values': [{'position': 4, 'id': '_Z', 'name': 'Not applicable'}]},
 {'id': 'TEACH_EXPERIENCE',
  'name': 'Teaching experience',
  'keyPosition': 16,
  'role': None,
  'values': [{'position': 4, 'id': '_Z', 'name': 'Not applicable'}]},
 {'id': 'CONTRACT_TYPE',
  'name': 'Type of contract',
  'keyPosition': 17,
  'role': None,
  'values': [{'position': 4, 'id': '_Z', 'name': 'Not applicable'}]},
 {'id': 'COUNTRY_ORIGIN',
  'name': 'Country / region of origin',
  'keyPosition': 18,
  'role': None,
  'values': [{'position': 223, 'id': 'W00', 'name': 'All countries'}]},
 {'id': 'REGION_DEST',
  'name': 'Destination region',
  'keyPosition': 19,
  'role': None,
  'values': [{'position': 223, 'id': 'W00', 'name': 'All countries'}]},
 {'id': 'IMM_STATUS',
  'name': 'Immigration status',
  'keyPosition': 20,
  'role': None,
  'values': [{'position': 4, 'id': '_Z', 'name': 'Not applicable'}]},
 {'id': 'REF_AREA',
  'name': 'Reference area',
  'description': 'The country or geographic area to which the measured statistical phenomenon relates.',
  'keyPosition': 21,
  'role': None,
  'values': [{'position': 2, 'id': 'AE', 'name': 'United Arab Emirates'},
   {'position': 3, 'id': 'AF', 'name': 'Afghanistan'},
   {'position': 227,
    'id': 'AIMS_ASIA_PAC',
    'name': 'AIMS: Asia and the Pacific'},
   {'position': 228, 'id': 'AIMS_CAS', 'name': 'AIMS: Central Asia'},
   {'position': 229, 'id': 'AIMS_EAS', 'name': 'AIMS: East Asia'},
   {'position': 230,
    'id': 'AIMS_EAS_PAC',
    'name': 'AIMS: East Asia and the Pacific'},
   {'position': 232,
    'id': 'AIMS_SAS_WAS',
    'name': 'AIMS: South and West Asia'},
   {'position': 6, 'id': 'AL', 'name': 'Albania'},
   {'position': 7, 'id': 'AM', 'name': 'Armenia'},
   {'position': 8, 'id': 'AO', 'name': 'Angola'},
   {'position': 9, 'id': 'AR', 'name': 'Argentina'},
   {'position': 13, 'id': 'AW', 'name': 'Aruba'},
   {'position': 14, 'id': 'AZ', 'name': 'Azerbaijan'},
   {'position': 15, 'id': 'BA', 'name': 'Bosnia and Herzegovina'},
   {'position': 16, 'id': 'BB', 'name': 'Barbados'},
   {'position': 17, 'id': 'BD', 'name': 'Bangladesh'},
   {'position': 19, 'id': 'BF', 'name': 'Burkina Faso'},
   {'position': 20, 'id': 'BG', 'name': 'Bulgaria'},
   {'position': 21, 'id': 'BH', 'name': 'Bahrain'},
   {'position': 22, 'id': 'BI', 'name': 'Burundi'},
   {'position': 23, 'id': 'BJ', 'name': 'Benin'},
   {'position': 25, 'id': 'BN', 'name': 'Brunei Darussalam'},
   {'position': 26, 'id': 'BO', 'name': 'Bolivia (Plurinational State of)'},
   {'position': 27, 'id': 'BR', 'name': 'Brazil'},
   {'position': 29, 'id': 'BT', 'name': 'Bhutan'},
   {'position': 30, 'id': 'BW', 'name': 'Botswana'},
   {'position': 31, 'id': 'BY', 'name': 'Belarus'},
   {'position': 34, 'id': 'CD', 'name': 'Democratic Republic of the Congo'},
   {'position': 35, 'id': 'CF', 'name': 'Central African Republic'},
   {'position': 36, 'id': 'CG', 'name': 'Congo'},
   {'position': 38, 'id': 'CI', 'name': "Côte d'Ivoire"},
   {'position': 40, 'id': 'CL', 'name': 'Chile'},
   {'position': 41, 'id': 'CM', 'name': 'Cameroon'},
   {'position': 42, 'id': 'CN', 'name': 'China'},
   {'position': 43, 'id': 'CO', 'name': 'Colombia'},
   {'position': 44, 'id': 'CR', 'name': 'Costa Rica'},
   {'position': 46, 'id': 'CU', 'name': 'Cuba'},
   {'position': 47, 'id': 'CV', 'name': 'Cabo Verde'},
   {'position': 49, 'id': 'CY', 'name': 'Cyprus'},
   {'position': 55, 'id': 'DO', 'name': 'Dominican Republic'},
   {'position': 56, 'id': 'DZ', 'name': 'Algeria'},
   {'position': 57, 'id': 'EC', 'name': 'Ecuador'},
   {'position': 58, 'id': 'EE', 'name': 'Estonia'},
   {'position': 59, 'id': 'EG', 'name': 'Egypt'},
   {'position': 61, 'id': 'ER', 'name': 'Eritrea'},
   {'position': 62, 'id': 'ES', 'name': 'Spain'},
   {'position': 63, 'id': 'ET', 'name': 'Ethiopia'},
   {'position': 70, 'id': 'GA', 'name': 'Gabon'},
   {'position': 72, 'id': 'GD', 'name': 'Grenada'},
   {'position': 73, 'id': 'GE', 'name': 'Georgia'},
   {'position': 75, 'id': 'GH', 'name': 'Ghana'},
   {'position': 77, 'id': 'GM', 'name': 'Gambia'},
   {'position': 78, 'id': 'GN', 'name': 'Guinea'},
   {'position': 79, 'id': 'GP', 'name': 'Guadeloupe'},
   {'position': 233, 'id': 'GPE_FEB_2016', 'name': 'GPE: (February 2016)'},
   {'position': 234,
    'id': 'GPE_FRA_FY16',
    'name': 'GPE: Fragile or conflict-affected (FY16, July 2018)'},
   {'position': 236, 'id': 'GPE_JUL_2018', 'name': 'GPE: (July 2018)'},
   {'position': 237,
    'id': 'GPE_NON_FRA_FY16',
    'name': 'GPE: Non-fragile and non-conflict-affected (FY16, July 2018)'},
   {'position': 80, 'id': 'GQ', 'name': 'Equatorial Guinea'},
   {'position': 81, 'id': 'GR', 'name': 'Greece'},
   {'position': 82, 'id': 'GT', 'name': 'Guatemala'},
   {'position': 84, 'id': 'GW', 'name': 'Guinea-Bissau'},
   {'position': 85, 'id': 'GY', 'name': 'Guyana'},
   {'position': 87, 'id': 'HN', 'name': 'Honduras'},
   {'position': 88, 'id': 'HR', 'name': 'Croatia'},
   {'position': 89, 'id': 'HT', 'name': 'Haiti'},
   {'position': 90, 'id': 'HU', 'name': 'Hungary'},
   {'position': 91, 'id': 'ID', 'name': 'Indonesia'},
   {'position': 95, 'id': 'IN', 'name': 'India'},
   {'position': 96, 'id': 'IQ', 'name': 'Iraq'},
   {'position': 97, 'id': 'IR', 'name': 'Iran (Islamic Republic of)'},
   {'position': 99, 'id': 'IT', 'name': 'Italy'},
   {'position': 100, 'id': 'JM', 'name': 'Jamaica'},
   {'position': 101, 'id': 'JO', 'name': 'Jordan'},
   {'position': 103, 'id': 'KE', 'name': 'Kenya'},
   {'position': 104, 'id': 'KG', 'name': 'Kyrgyzstan'},
   {'position': 105, 'id': 'KH', 'name': 'Cambodia'},
   {'position': 107, 'id': 'KM', 'name': 'Comoros'},
   {'position': 109,
    'id': 'KP',
    'name': "Democratic People's Republic of Korea"},
   {'position': 111, 'id': 'KW', 'name': 'Kuwait'},
   {'position': 112, 'id': 'KY', 'name': 'Cayman Islands'},
   {'position': 113, 'id': 'KZ', 'name': 'Kazakhstan'},
   {'position': 114, 'id': 'LA', 'name': "Lao People's Democratic Republic"},
   {'position': 115, 'id': 'LB', 'name': 'Lebanon'},
   {'position': 118, 'id': 'LK', 'name': 'Sri Lanka'},
   {'position': 119, 'id': 'LR', 'name': 'Liberia'},
   {'position': 120, 'id': 'LS', 'name': 'Lesotho'},
   {'position': 121, 'id': 'LT', 'name': 'Lithuania'},
   {'position': 123, 'id': 'LV', 'name': 'Latvia'},
   {'position': 124, 'id': 'LY', 'name': 'Libya'},
   {'position': 125, 'id': 'MA', 'name': 'Morocco'},
   {'position': 127, 'id': 'MD', 'name': 'Republic of Moldova'},
   {'position': 239,
    'id': 'MDG_CAU_CEN_ASIA',
    'name': 'MDG: Caucasus and Central Asia'},
   {'position': 240,
    'id': 'MDG_DEVELOPED_REG',
    'name': 'MDG: Developed regions'},
   {'position': 241,
    'id': 'MDG_DEVELOPING_REG',
    'name': 'MDG: Developing regions'},
   {'position': 242, 'id': 'MDG_EAS', 'name': 'MDG: Eastern Asia'},
   {'position': 244,
    'id': 'MDG_LAC',
    'name': 'MDG: Latin America and the Caribbean'},
   {'position': 245, 'id': 'MDG_LAC_CAR', 'name': 'MDG: Caribbean'},
   {'position': 246, 'id': 'MDG_LAC_LA', 'name': 'MDG: Latin America'},
   {'position': 247, 'id': 'MDG_NAFR', 'name': 'MDG: Northern Africa'},
   {'position': 248, 'id': 'MDG_OCE', 'name': 'MDG: Oceania'},
   {'position': 249, 'id': 'MDG_SAS', 'name': 'MDG: Southern Asia'},
   {'position': 250,
    'id': 'MDG_SAS_NOINDIA',
    'name': 'MDG: Southern Asia (excluding India)'},
   {'position': 251, 'id': 'MDG_SEAS', 'name': 'MDG: South-eastern Asia'},
   {'position': 252, 'id': 'MDG_SSA', 'name': 'MDG: Sub-Saharan Africa'},
   {'position': 253, 'id': 'MDG_WEST_AS', 'name': 'MDG: Western Asia'},
   {'position': 254, 'id': 'MDG_WORLD', 'name': 'MDG: World'},
   {'position': 128, 'id': 'ME', 'name': 'Montenegro'},
   {'position': 129, 'id': 'MG', 'name': 'Madagascar'},
   {'position': 130, 'id': 'MH', 'name': 'Marshall Islands'},
   {'position': 131, 'id': 'MK', 'name': 'North Macedonia'},
   {'position': 132, 'id': 'ML', 'name': 'Mali'},
   {'position': 133, 'id': 'MM', 'name': 'Myanmar'},
   {'position': 134, 'id': 'MN', 'name': 'Mongolia'},
   {'position': 135,
    'id': 'MO',
    'name': 'China, Macao Special Administrative Region'},
   {'position': 137, 'id': 'MQ', 'name': 'Martinique'},
   {'position': 138, 'id': 'MR', 'name': 'Mauritania'},
   {'position': 140, 'id': 'MT', 'name': 'Malta'},
   {'position': 141, 'id': 'MU', 'name': 'Mauritius'},
   {'position': 142, 'id': 'MV', 'name': 'Maldives'},
   {'position': 143, 'id': 'MW', 'name': 'Malawi'},
   {'position': 144, 'id': 'MX', 'name': 'Mexico'},
   {'position': 145, 'id': 'MY', 'name': 'Malaysia'},
   {'position': 146, 'id': 'MZ', 'name': 'Mozambique'},
   {'position': 147, 'id': 'NA', 'name': 'Namibia'},
   {'position': 148, 'id': 'NC', 'name': 'New Caledonia'},
   {'position': 149, 'id': 'NE', 'name': 'Niger'},
   {'position': 150, 'id': 'NG', 'name': 'Nigeria'},
   {'position': 151, 'id': 'NI', 'name': 'Nicaragua'},
   {'position': 154, 'id': 'NP', 'name': 'Nepal'},
   {'position': 158, 'id': 'OM', 'name': 'Oman'},
   {'position': 159, 'id': 'PA', 'name': 'Panama'},
   {'position': 160, 'id': 'PE', 'name': 'Peru'},
   {'position': 162, 'id': 'PG', 'name': 'Papua New Guinea'},
   {'position': 163, 'id': 'PH', 'name': 'Philippines'},
   {'position': 164, 'id': 'PK', 'name': 'Pakistan'},
   {'position': 165, 'id': 'PL', 'name': 'Poland'},
   {'position': 166, 'id': 'PR', 'name': 'Puerto Rico'},
   {'position': 167, 'id': 'PS', 'name': 'Palestine'},
   {'position': 168, 'id': 'PT', 'name': 'Portugal'},
   {'position': 169, 'id': 'PW', 'name': 'Palau'},
   {'position': 170, 'id': 'PY', 'name': 'Paraguay'},
   {'position': 171, 'id': 'QA', 'name': 'Qatar'},
   {'position': 173, 'id': 'RO', 'name': 'Romania'},
   {'position': 174, 'id': 'RS', 'name': 'Serbia'},
   {'position': 175, 'id': 'RU', 'name': 'Russian Federation'},
   {'position': 176, 'id': 'RW', 'name': 'Rwanda'},
   {'position': 177, 'id': 'SA', 'name': 'Saudi Arabia'},
   {'position': 179, 'id': 'SC', 'name': 'Seychelles'},
   {'position': 180, 'id': 'SD', 'name': 'Sudan'},
   {'position': 255, 'id': 'SDG_CAS', 'name': 'SDG: Asia (Central)'},
   {'position': 256,
    'id': 'SDG_CEN_SAS',
    'name': 'SDG: Asia (Central and Southern)'},
   {'position': 257, 'id': 'SDG_EAS', 'name': 'SDG: Asia (Eastern)'},
   {'position': 258,
    'id': 'SDG_EAS_SEAS',
    'name': 'SDG: Asia (Eastern and South-eastern)'},
   {'position': 259, 'id': 'SDG_EUR', 'name': 'SDG: Europe'},
   {'position': 260,
    'id': 'SDG_EUR_NAM',
    'name': 'SDG: Northern America and Europe'},
   {'position': 261,
    'id': 'SDG_LAC',
    'name': 'SDG: Latin America and the Caribbean'},
   {'position': 262,
    'id': 'SDG_LDC',
    'name': 'SDG: Least Developed Countries'},
   {'position': 263,
    'id': 'SDG_LLDC',
    'name': 'SDG: Landlocked Developing Countries'},
   {'position': 264, 'id': 'SDG_NAFR', 'name': 'SDG: Africa (Northern)'},
   {'position': 265,
    'id': 'SDG_NAFR_WEST_AS',
    'name': 'SDG: Western Asia and Northern Africa'},
   {'position': 269,
    'id': 'SDG_OCEX_AUS_NZ',
    'name': 'SDG: Oceania (excl. Australia/New Zealand)'},
   {'position': 270, 'id': 'SDG_SAS', 'name': 'SDG: Asia (Southern)'},
   {'position': 271, 'id': 'SDG_SEAS', 'name': 'SDG: Asia (South-eastern)'},
   {'position': 272,
    'id': 'SDG_SIDS',
    'name': 'SDG: Small Island Developing States'},
   {'position': 273, 'id': 'SDG_SSA', 'name': 'SDG: Africa (Sub-Saharan)'},
   {'position': 274, 'id': 'SDG_WEST_AS', 'name': 'SDG: Asia (Western)'},
   {'position': 275, 'id': 'SDG_WORLD', 'name': 'SDG: World'},
   {'position': 182, 'id': 'SG', 'name': 'Singapore'},
   {'position': 183, 'id': 'SI', 'name': 'Slovenia'},
   {'position': 185, 'id': 'SL', 'name': 'Sierra Leone'},
   {'position': 187, 'id': 'SN', 'name': 'Senegal'},
   {'position': 189, 'id': 'SR', 'name': 'Suriname'},
   {'position': 190, 'id': 'SS', 'name': 'South Sudan'},
   {'position': 191, 'id': 'ST', 'name': 'Sao Tome and Principe'},
   {'position': 192, 'id': 'SV', 'name': 'El Salvador'},
   {'position': 194, 'id': 'SY', 'name': 'Syrian Arab Republic'},
   {'position': 195, 'id': 'SZ', 'name': 'Eswatini'},
   {'position': 197, 'id': 'TD', 'name': 'Chad'},
   {'position': 198, 'id': 'TG', 'name': 'Togo'},
   {'position': 199, 'id': 'TH', 'name': 'Thailand'},
   {'position': 200, 'id': 'TJ', 'name': 'Tajikistan'},
   {'position': 202, 'id': 'TL', 'name': 'Timor-Leste'},
   {'position': 203, 'id': 'TM', 'name': 'Turkmenistan'},
   {'position': 204, 'id': 'TN', 'name': 'Tunisia'},
   {'position': 205, 'id': 'TO', 'name': 'Tonga'},
   {'position': 206, 'id': 'TR', 'name': 'Turkey'},
   {'position': 207, 'id': 'TT', 'name': 'Trinidad and Tobago'},
   {'position': 209, 'id': 'TZ', 'name': 'United Republic of Tanzania'},
   {'position': 210, 'id': 'UA', 'name': 'Ukraine'},
   {'position': 211, 'id': 'UG', 'name': 'Uganda'},
   {'position': 276, 'id': 'UIS_ARAB', 'name': 'UIS: Arab States'},
   {'position': 277, 'id': 'UIS_CAS', 'name': 'UIS: Central Asia'},
   {'position': 278,
    'id': 'UIS_CEN_EEUR',
    'name': 'UIS: Central and Eastern Europe'},
   {'position': 279,
    'id': 'UIS_EAP',
    'name': 'UIS: East Asia and the Pacific'},
   {'position': 280,
    'id': 'UIS_LAC',
    'name': 'UIS: Latin America and the Caribbean'},
   {'position': 282, 'id': 'UIS_SAS_WAS', 'name': 'UIS: South and West Asia'},
   {'position': 283, 'id': 'UIS_SIDS', 'name': 'UNESCO: SIDS'},
   {'position': 284, 'id': 'UIS_SSA', 'name': 'UIS: Sub-Saharan Africa'},
   {'position': 285, 'id': 'UIS_WORLD', 'name': 'UIS: World'},
   {'position': 286, 'id': 'UNICEF_AFRICA', 'name': 'UNICEF: Africa'},
   {'position': 287,
    'id': 'UNICEF_ALL',
    'name': 'UNICEF: All UNICEF Countries'},
   {'position': 288, 'id': 'UNICEF_ASIA', 'name': 'UNICEF: Asia'},
   {'position': 289,
    'id': 'UNICEF_CEE_CIS',
    'name': 'UNICEF: Central and Eastern Europe/Commonwealth of Independent States'},
   {'position': 290,
    'id': 'UNICEF_DEVELOPING',
    'name': 'UNICEF: Developing countries'},
   {'position': 291,
    'id': 'UNICEF_EAP',
    'name': 'UNICEF: East Asia and Pacific'},
   {'position': 293,
    'id': 'UNICEF_ESEAFR',
    'name': 'UNICEF: Eastern and Southern Africa'},
   {'position': 296,
    'id': 'UNICEF_LAC',
    'name': 'UNICEF: Latin America and Caribbean'},
   {'position': 297,
    'id': 'UNICEF_LDC',
    'name': 'UNICEF: Least developed countries'},
   {'position': 298,
    'id': 'UNICEF_MENA',
    'name': 'UNICEF: Middle East and North Africa'},
   {'position': 301, 'id': 'UNICEF_SASIA', 'name': 'UNICEF: South Asia'},
   {'position': 302, 'id': 'UNICEF_SSA', 'name': 'UNICEF: Sub-Saharan Africa'},
   {'position': 303,
    'id': 'UNICEF_WCAFR',
    'name': 'UNICEF: West and Central Africa'},
   {'position': 305, 'id': 'UNICEF_WORLD', 'name': 'UNICEF: World'},
   {'position': 213, 'id': 'UY', 'name': 'Uruguay'},
   {'position': 214, 'id': 'UZ', 'name': 'Uzbekistan'},
   {'position': 216, 'id': 'VE', 'name': 'Venezuela (Bolivarian Republic of)'},
   {'position': 219, 'id': 'VN', 'name': 'Viet Nam'},
   {'position': 220, 'id': 'VU', 'name': 'Vanuatu'},
   {'position': 306,
    'id': 'WB_18F',
    'name': 'WB: FY18 IDA countries classified as fragile situations'},
   {'position': 307,
    'id': 'WB_18T',
    'name': 'WB: FY18 IDA & IBRD countries classified as fragile situations'},
   {'position': 308, 'id': 'WB_ARAB', 'name': 'WB: Arab World'},
   {'position': 309,
    'id': 'WB_CAR_SMALL',
    'name': 'WB: Caribbean small states'},
   {'position': 311, 'id': 'WB_EAP', 'name': 'WB: East Asia & Pacific'},
   {'position': 312,
    'id': 'WB_EAP_IBRD',
    'name': 'WB: East Asia & Pacific (IBRD only)'},
   {'position': 313,
    'id': 'WB_EAP_IBRD_IDA',
    'name': 'WB: East Asia & Pacific (IDA & IBRD)'},
   {'position': 314,
    'id': 'WB_EAP_IDA',
    'name': 'WB: East Asia & Pacific (IDA total)'},
   {'position': 315,
    'id': 'WB_EAP_X_HIC',
    'name': 'WB: East Asia & Pacific (excluding high income)'},
   {'position': 316,
    'id': 'WB_EARLY_DIV_GMR',
    'name': 'WB: Early-demographic dividend'},
   {'position': 317, 'id': 'WB_ECAS', 'name': 'WB: Europe & Central Asia'},
   {'position': 318,
    'id': 'WB_ECAS_IBRD',
    'name': 'WB: Europe & Central Asia (IBRD only)'},
   {'position': 319,
    'id': 'WB_ECAS_IBRD_IDA',
    'name': 'WB: Europe & Central Asia (IDA & IBRD)'},
   {'position': 320,
    'id': 'WB_ECAS_IDA',
    'name': 'WB: Europe & Central Asia (IDA total)'},
   {'position': 321,
    'id': 'WB_ECAS_X_HIC',
    'name': 'WB: Europe & Central Asia (excluding high income)'},
   {'position': 322, 'id': 'WB_EU', 'name': 'WB: European Union'},
   {'position': 323,
    'id': 'WB_FCAS',
    'name': 'WB: Fragile and conflict affected situations'},
   {'position': 324,
    'id': 'WB_GPE',
    'name': 'WB: Global Partnership for Education (July 2018)'},
   {'position': 326,
    'id': 'WB_HIPC',
    'name': 'WB: Heavily Indebted Poor Countries (HIPC)'},
   {'position': 327, 'id': 'WB_I18', 'name': 'WB: FY18 IDA total'},
   {'position': 328, 'id': 'WB_IBRD', 'name': 'WB: IBRD only'},
   {'position': 329, 'id': 'WB_IBRD_IDA', 'name': 'WB: IDA & IBRD total'},
   {'position': 330,
    'id': 'WB_IBRD_IDA_FCAS',
    'name': 'WB: IDA & IBRD countries classified as fragile situations'},

In [14]:
# define the function
# input: new indicator code 
# output: related metadata dictionary

def find_idctr_dict(new_code):
    url = 'https://api.uis.unesco.org/sdmx/data/' + new_code + '?startPeriod=2000&endPeriod=2018&format=sdmx-json&includeMetadata=true&locale=en'
    resp = requests.get(url, headers = headers)
    doc = resp.json()
    dict_dimensions =  {item['id']:{k:item[k] for k in ('name','description','values') if k in item.keys() } for item in doc['structure']['dimensions']['series']}
    dict_attributes =  {item['id']:{k:item[k] for k in ('name','description','values') if k in item.keys() } for item in doc['structure']['attributes']['observation']}
    dict_dimensions =  {item['id']:{k:item[k] for k in ('name','description','values') if k in item.keys() } for item in doc['structure']['dimensions']['series']}
    dict_all = {**dict_dimensions, **dict_attributes}
    return dict_all

### Example: Translating an existing indicator csv file

In [15]:
# take first indicator as example
new_code = idctr.loc[0,'New_Code']
file = idctr.Indicator[0] + ' ' + idctr.Disaggregation[0] + '.csv'
data = pd.read_csv('..\\data\\UNESCO_UIS_indicators\\'+file).astype(str)

data
meta = find_idctr_dict(new_code)
for col in data.columns:
    if col == 'TIME_PERIOD' or col == 'OBS_VALUE':  # these 2 columns are self-explanatory
        continue
    col_elem_dict = {str(item['id']):item['name'] for item in meta[col]['values']}
    data[col].replace(col_elem_dict, inplace = True)

col_dict = {k:meta[k]['name'] for k in meta}
data.rename(columns = col_dict, inplace = True)
data # seems quite readable

,STAT_UNIT,UNIT_MEASURE,EDU_LEVEL,EDU_CAT,SEX,AGE,GRADE,SECTOR_EDU,EDU_ATTAIN,WEALTH_QUINTILE,...,COUNTRY_ORIGIN,REGION_DEST,IMM_STATUS,REF_AREA,TIME_PERIOD,OBS_VALUE,UNIT_MULT,OBS_STATUS,FREQ,DECIMALS
0,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AE,2005,95.00645,0,A,A,5
1,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AF,2011,46.99005,0,A,A,5
2,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2000,86.70137,0,A,A,5
3,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2001,86.67913,0,A,A,5
4,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2002,87.19672,0,A,A,5
5,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2003,87.84177,0,A,A,5
6,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2004,88.79763,0,A,A,5
7,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2005,89.27566,0,A,A,5
8,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2006,89.71869000000001,0,A,A,5
9,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2007,90.01857,0,A,A,5
10,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2008,91.15777,0,A,A,5
11,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2009,91.49819000000001,0,A,A,5
12,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2010,91.53687,0,A,A,5
13,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2011,91.05581,0,A,A,5
14,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2012,92.39081999999999,0,A,A,5
15,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2013,92.58596,0,A,A,5
16,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2014,92.93443,0,A,A,5
17,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2015,93.21709,0,A,A,5
18,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_ASIA_PAC,2016,93.49934,0,A,A,5
19,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_CAS,2000,99.84123000000001,0,A,A,5
20,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_CAS,2001,99.84487,0,A,A,5
21,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_CAS,2002,99.84839000000001,0,A,A,5
22,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_CAS,2003,99.85271,0,A,A,5
23,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_CAS,2004,99.85623000000001,0,A,A,5
24,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_CAS,2005,99.85915,0,A,A,5
25,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_CAS,2006,99.87165999999999,0,A,A,5
26,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_CAS,2007,99.87321,0,A,A,5
27,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_CAS,2008,99.87437,0,A,A,5
28,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_CAS,2009,99.90626,0,A,A,5
29,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,AIMS_CAS,2010,99.92108,0,A,A,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2617,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WM_EMU,2001,99.54435,0,E,A,5
2618,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WM_EMU,2002,99.56338000000001,0,E,A,5
2619,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WM_EMU,2003,99.62899,0,E,A,5
2620,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WM_EMU,2004,99.7083,0,A,A,5
2621,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WM_EMU,2005,99.72292,0,E,A,5
2622,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WM_EMU,2006,99.70186,0,E,A,5
2623,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WM_EMU,2007,99.7318,0,E,A,5
2624,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WM_EMU,2008,99.70413,0,E,A,5
2625,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WM_EMU,2009,99.73253000000001,0,E,A,5
2626,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WM_EMU,2010,99.73781,0,E,A,5
2627,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WM_EMU,2011,99.72861999999999,0,E,A,5
2628,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WM_EMU,2012,99.73546999999999,0,E,A,5
2629,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WM_EMU,2013,99.74058000000001,0,E,A,5
2630,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WM_EMU,2014,99.75189,0,A,A,5
2631,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WM_EMU,2015,99.74794,0,E,A,5
2632,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WM_EMU,2016,99.74857,0,E,A,5
2633,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,WS,2011,99.23566,0,A,A,5
2634,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,YE,2004,77.0,0,E,A,5
2635,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,ZA,2007,97.57078,0,A,A,5
2636,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,ZA,2009,98.36509000000001,0,A,A,5
2637,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,ZA,2010,98.64413,0,A,A,5
2638,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,ZA,2011,98.78966,0,A,A,5
2639,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,ZA,2012,98.88204,0,A,A,5
2640,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,ZA,2014,98.88228000000001,0,A,A,5
2641,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,ZA,2015,98.95578,0,A,A,5
2642,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,ZM,2002,69.08881,0,A,A,5
2643,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,ZM,2007,64.04964,0,E,A,5
2644,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,ZM,2010,88.71455999999999,0,A,A,5
2645,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,ZW,2011,90.9307,0,E,A,5
2646,LR,PT,_Z,_Z,_T,Y15T24,_Z,_Z,_Z,_Z,...,W00,W00,_Z,ZW,2014,90.42811999999999,0,E,A,5

,Statistical unit,Unit of measure,Level of education,Orientation,Sex,Age,Grade,Type of institution,Level of educational attainment,Wealth quintile,...,Country / region of origin,Destination region,Immigration status,Reference area,TIME_PERIOD,OBS_VALUE,Unit multiplier,Observation status,Frequency,Decimals
0,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,United Arab Emirates,2005,95.00645,Units,Normal,Annual,Five
1,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,Afghanistan,2011,46.99005,Units,Normal,Annual,Five
2,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2000,86.70137,Units,Normal,Annual,Five
3,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2001,86.67913,Units,Normal,Annual,Five
4,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2002,87.19672,Units,Normal,Annual,Five
5,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2003,87.84177,Units,Normal,Annual,Five
6,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2004,88.79763,Units,Normal,Annual,Five
7,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2005,89.27566,Units,Normal,Annual,Five
8,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2006,89.71869000000001,Units,Normal,Annual,Five
9,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2007,90.01857,Units,Normal,Annual,Five
10,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2008,91.15777,Units,Normal,Annual,Five
11,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2009,91.49819000000001,Units,Normal,Annual,Five
12,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2010,91.53687,Units,Normal,Annual,Five
13,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2011,91.05581,Units,Normal,Annual,Five
14,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2012,92.39081999999999,Units,Normal,Annual,Five
15,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2013,92.58596,Units,Normal,Annual,Five
16,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2014,92.93443,Units,Normal,Annual,Five
17,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2015,93.21709,Units,Normal,Annual,Five
18,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Asia and the Pacific,2016,93.49934,Units,Normal,Annual,Five
19,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Central Asia,2000,99.84123000000001,Units,Normal,Annual,Five
20,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Central Asia,2001,99.84487,Units,Normal,Annual,Five
21,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Central Asia,2002,99.84839000000001,Units,Normal,Annual,Five
22,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Central Asia,2003,99.85271,Units,Normal,Annual,Five
23,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Central Asia,2004,99.85623000000001,Units,Normal,Annual,Five
24,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Central Asia,2005,99.85915,Units,Normal,Annual,Five
25,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Central Asia,2006,99.87165999999999,Units,Normal,Annual,Five
26,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Central Asia,2007,99.87321,Units,Normal,Annual,Five
27,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Central Asia,2008,99.87437,Units,Normal,Annual,Five
28,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Central Asia,2009,99.90626,Units,Normal,Annual,Five
29,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,AIMS: Central Asia,2010,99.92108,Units,Normal,Annual,Five
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2617,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,WB: Euro area,2001,99.54435,Units,Estimated value,Annual,Five
2618,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,WB: Euro area,2002,99.56338000000001,Units,Estimated value,Annual,Five
2619,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,WB: Euro area,2003,99.62899,Units,Estimated value,Annual,Five
2620,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,WB: Euro area,2004,99.7083,Units,Normal,Annual,Five
2621,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,WB: Euro area,2005,99.72292,Units,Estimated value,Annual,Five
2622,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,WB: Euro area,2006,99.70186,Units,Estimated value,Annual,Five
2623,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,WB: Euro area,2007,99.7318,Units,Estimated value,Annual,Five
2624,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,WB: Euro area,2008,99.70413,Units,Estimated value,Annual,Five
2625,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,WB: Euro area,2009,99.73253000000001,Units,Estimated value,Annual,Five
2626,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,WB: Euro area,2010,99.73781,Units,Estimated value,Annual,Five
2627,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,WB: Euro area,2011,99.72861999999999,Units,Estimated value,Annual,Five
2628,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,WB: Euro area,2012,99.73546999999999,Units,Estimated value,Annual,Five
2629,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,WB: Euro area,2013,99.74058000000001,Units,Estimated value,Annual,Five
2630,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,WB: Euro area,2014,99.75189,Units,Normal,Annual,Five
2631,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,WB: Euro area,2015,99.74794,Units,Estimated value,Annual,Five
2632,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,WB: Euro area,2016,99.74857,Units,Estimated value,Annual,Five
2633,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,Samoa,2011,99.23566,Units,Normal,Annual,Five
2634,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,Yemen,2004,77.0,Units,Estimated value,Annual,Five
2635,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,South Africa,2007,97.57078,Units,Normal,Annual,Five
2636,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,South Africa,2009,98.36509000000001,Units,Normal,Annual,Five
2637,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,South Africa,2010,98.64413,Units,Normal,Annual,Five
2638,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,South Africa,2011,98.78966,Units,Normal,Annual,Five
2639,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,South Africa,2012,98.88204,Units,Normal,Annual,Five
2640,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,South Africa,2014,98.88228000000001,Units,Normal,Annual,Five
2641,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,South Africa,2015,98.95578,Units,Normal,Annual,Five
2642,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,Zambia,2002,69.08881,Units,Normal,Annual,Five
2643,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,Zambia,2007,64.04964,Units,Estimated value,Annual,Five
2644,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,Zambia,2010,88.71455999999999,Units,Normal,Annual,Five
2645,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,Zimbabwe,2011,90.9307,Units,Estimated value,Annual,Five
2646,Literacy rate,Percentage,Not applicable,Not applicable,Total,15-24 years,Not applicable,Not applicable,Not applicable,Not applicable,...,All countries,All countries,Not applicable,Zimbabwe,2014,90.42811999999999,Units,Estimated value,Annual,Five